#pragma once

// PL0Compiler
#include <parser/HelperFunctions.hpp>
#include <parser/Parser.hpp>
#include <parser/detail/ParserBase.hpp>
#include <parser/detail/AssignStmt.hpp>
#include <parser/detail/BlockUnit.hpp>
#include <parser/detail/CallStmt.hpp>
#include <parser/detail/CompoundStmt.hpp>
#include <parser/detail/CondStmt.hpp>
#include <parser/detail/ConstDeclStmt.hpp>
#include <parser/detail/ConstVarDecl.hpp>
#include <parser/detail/Expression.hpp>
#include <parser/detail/IdentRefExpression.hpp>
#include <parser/detail/IfStmt.hpp>
#include <parser/detail/IntegerLiteral.hpp>
#include <parser/detail/MultiplicativeExpression.hpp>
#include <parser/detail/PrimaryExpression.hpp>
#include <parser/detail/ProcedureDecl.hpp>
#include <parser/detail/ProcedureRefExpression.hpp>
#include <parser/detail/ProcedureUnit.hpp>
#include <parser/detail/ProgramUnit.hpp>
#include <parser/detail/Statement.hpp>
#include <parser/detail/UnaryExpression.hpp>
#include <parser/detail/VarDecl.hpp>
#include <parser/detail/VarDeclStmt.hpp>
#include <parser/detail/WhileStmt.hpp>

